In [1]:
import numpy as np 

In [2]:
arr =  np.array([1,2,3])


In [3]:
arr

array([1, 2, 3])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [15]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [16]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [17]:
myarr.shape

(4, 3)

In [18]:
myarr.size

12

In [19]:
myarr.ndim

2

In [20]:
myarr.dtype

dtype('int64')

In [21]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float32')

In [22]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [24]:
n = myarr.astype('float64')

In [25]:
n.dtype

dtype('float64')

In [26]:
resaped = myarr.reshape(3,4)

In [28]:
resaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., 13.]], dtype=float32)

In [29]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)